### ISSUE TITLE
Support version switching

### ISSUE THREAD

**Issue by fago** [SimpliField/ansible-node#9]
When the role is installed initially with nodejs 6.x, and the variable is changed to 4.x later on, then it fails to install nodejs in 4.*. This is, as the role just adds a second ppa but apt keeps the higher version package installed.

As workaround I figured that a task like
```
- name: Ensure Node.js and npm are installed.
  become: yes
  apt: "name=nodejs={{ nodejs_version|regex_replace('x', '') }}* state=present"
```
solves it. It still keeps both ppas around, but at least the right version of nodejs is installed.

**Comment by SebastienElet** [comment]
Hello, why you did not change the variable at the initial setup ?

```yaml
- roles:
  - role: SimpliField.node
    nodejs_version: 4.x
```

**Comment by fago** [comment]
Because I missed it. Point is, when you change it later on it does not work.

**Comment by SebastienElet** [comment]
Ok, i got it.

I use playbooks like this to upgrade
```yaml
---
- hosts: server
  become: true

  roles:
    - role: SimpliField.node
      nodejs_version: "8.x"

  post_tasks:
  - name: remove node 6.0 source.list
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_6.x wheezy main"
      state: absent

  - name: install latest node version
    apt:
      pkg: nodejs
      update-cache: yes
      state: latest
```

I will see to ensure remove old source & ensure node version in the role.

Thanks for your feedback !
